# ---------------
# Server
# ---------------
server:
  port: 3000

# --------------
# ActiveMq
# --------------
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    non-blocking-redelivery: true
    packages:
      trust-all: true